### ISSUE TITLE
Graphical Date Picker

### ISSUE THREAD

**Issue by val99erie** [curationexperts/tufts-election#3]
Background:
At one point, the application supported a graphical date picker for the election year facet. This capability was removed when modifications were made to make the application more accessible to users using screen reader software. Tufts would like this capability added back to the application.

Acceptance Criteria:
- [x] Replace the election year facet with a graphical date picker.  (See:  https://github.com/projectblacklight/blacklight_range_limit)
- [x] Ensure that the start date field, end date field, and ‘limit’ (select) button are tab accessible.
- [x] Ensure that the start date and end date field have screen reader compatible labels which are hidden to normal browser users.

For reference:
https://github.com/TuftsUniversity/tufts-election/issues/12

**Comment by tonyc** [comment]
Closed in https://github.com/curationexperts/tufts-election/pull/8
