### ISSUE TITLE
Read Candidate Name Authorities from Fedora

### ISSUE THREAD

**Issue by val99erie** [curationexperts/tufts-election#4]
Background:
The candidate name authority files are currently read from disk on the server. Tufts would like the authority data to be supplied directly from Fedora.

Tufts will:  Provide an unzipped copy of the party-authority.xml file stored in an appropriate object in Fedora.

The authority data is loaded on server start-up.

For reference:
https://github.com/TuftsUniversity/tufts-election/issues/10

Acceptance Criteria:

- [x] Alter existing code that loads candidate name authorities, so that it loads from the authority file(s) in fedora instead of from files on the hard drive.  Read the candidate name authority from the fedora object stored at tufts:MS115.003.001.00002.00001
- [x] Leave the remaining functionality for the candidate name mappings unchanged.
- [x] Code to load name authorities should run on server startup

**Comment by mark-dce** [comment]
The live production copy of the candidate file can be downloaded from http://dl.tufts.edu/catalog/tufts:MS115.003.001.00002.00001
