### ISSUE TITLE
Read Party Authorities from Fedora and Display Party Information

### ISSUE THREAD

**Issue by val99erie** [curationexperts/tufts-election#5]
Background:
Tufts would like to read the party authority data directly from Fedora. In addition to reading the ID mappings from Fedora, Tufts would like the supplemental party authority data displayed when a specific party is chosen from the facets.

The authority data is loaded on server start-up.

For reference:  https://github.com/TuftsUniversity/tufts-election/issues/13
There is a wireframe of the new UI in the old Tufts ticket.

Acceptance Criteria:
- [x] Clean up party-authority.xml content in various places to close "p" tags, etc.
- [x] Alter existing code that loads party authorities, so that it loads from the authority file(s) in fedora instead of from files on the hard drive.
- [x] ~~Make necessary changes to group the party facet by party ID. NOTE: if multiple name-to-ID mappings exist for the same party ID, the system will use the last mapping read from the authority file.~~
- [x] Add a css div which will display supplemental party information when an individual party has been selected using the facet sidebar. The data will be displayed as HTML (html tags honored, xml tags removed.)  Any HTML included in the authority file descriptions must be validated outside the application. The application will display the HTML as-is and may not display invalid HTML properly.
- [x] Remove party-authority.xml from config/ and switch path in initializer to tmp/ when file is on production Fedora server.

**Comment by val99erie** [comment]
Question:  
According to the SOW, Tufts will:  Provide an unzipped copy of the party-authority.xml file stored in an appropriate object in Fedora.

Have they done this?  Do we know the fedora ID for that object?

**Comment by mark-dce** [comment]
The party authority can be found at http://dl.tufts.edu/catalog/tufts:party-authority
