### ISSUE TITLE
Read State Authorities from Fedora and Display State Information

### ISSUE THREAD

**Issue by tonyc** [curationexperts/tufts-election#7]
References https://github.com/TuftsUniversity/tufts-election/issues/9

Tufts would like to read the state authority data directly from Fedora. In addition to reading the ID mappings from Fedora, Tufts would like the supplemental office authority data displayed when a specific state is chosen from the facet sidebar. Tufts would also like to display an image for the state and additional bibliography data stored in a separate bibliography file.

## Tufts will:

* Provide an unzipped copy of state authority data stored in an appropriate Fedora object.
* Provide an unzipped copy of the bibliographic data for each state stored in an appropriate Fedora object. If each state bibliography is stored in a separate object, the state authority file should include the PID for each state’s bibliography file.
* Document the mechanism to access state images (state_images ---> images ---> aas_portal directory) and provide DCE access to or a copy of the images.

## DCE Will:

- [x] Implement code to load the state authority and bibliographic data on server startup (updates to the candidate authorities will require a server restart) 
- [x] Read the state authority from the fedora object stored in the defined Fedora object.
- [x] Read the state bibliography data from the appropriate Fedora object.
- [x] Add a css div which will display 
  - [x] The state image
  - [x] The content in the <description> node of each authority entry. The data will be displayed as HTML (html tags honored, xml tags removed.
  - [x] The content in the associated bibliography file. The data will be displayed as formatted HTML
- [x] Any HTML included in the authority descriptions and bibliography must be validated outside the application. The application will display the HTML as-is and may not display invalid HTML properly.

**Comment by mark-dce** [comment]
The state authority file can be found at http://dl.tufts.edu/catalog/tufts:state-authority

**Comment by val99erie** [comment]
Question for @mark-dce 
I'm having trouble finding the state images.  A comment in the original story says:
"The individual state images can be found in the state_images ---> images ---> aas_portal directory."
Is there a nice URL or something that can get us there?

**Comment by val99erie** [comment]
@mark-dce : Never mind.  I see some images in app/assets/images/state_images/*.gif

**Comment by mark-dce** [comment]
@val99erie - yup that's them

**Comment by tonyc** [comment]
:shipit:
